vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|04 Sep 2020 14:38:53 -0000
vti_extenderversion:SR|12.0.0.6500
vti_author:SR|LAPTOP-3VENH845\\Administrator
vti_modifiedby:SR|LAPTOP-3VENH845\\Administrator
vti_timecreated:TR|04 Sep 2020 14:38:53 -0000
vti_cacheddtm:TX|04 Sep 2020 14:38:53 -0000
vti_filesize:IR|16944
vti_cachedtitle:SR|Nuh's Ark Islamic Montessori School
vti_cachedbodystyle:SR|<body>
vti_cachedlinkinfo:VX|Q|https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css S|https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js S|https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js Q|https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css H|dashboard.php H|../index.php K|dashboard.php K|dashboard.php H|account-transaction_add-transaction.php H|account-transaction_summary.php K|dashboard.php H|account-transaction_add-transaction.php H|account-transaction_annual_summary.php K|dashboard.php H|payslip_select-staff.php H|payslip_summary.php H|report_expense-report.php K|dashboard.php K|dashboard.php H|invoice_select-student.php H|invoice_select-invoice.php K|dashboard.php H|payment_select-student.php H|payment_summary.php K|dashboard.php H|account-transaction_incomes_add-transaction.php H|account-transaction_incomes.php H|report_payment-report.php K|dashboard.php H|account-statement.php H|account-statement_search.php K|dashboard.php H|invoice_paid.php H|invoice_partial.php H|invoice_unpaid.php K|dashboard.php K|dashboard.php H|student_new-account.php H|student_manage-account.php K|dashboard.php K|dashboard.php H|staff_new-account.php H|staff_manage-account.php H|staff-directory.php K|dashboard.php K|dashboard.php H|report_account-statement-report.php H|report_account-statement-report-annual.php H|account-statement.php H|report_expense-report.php H|report_payment-report.php H|report_payslip-report.php H|report_annual-fees-report.php H|report_term-fees-report.php H|../nuhsark/dashboard.php H|../logout.php Q|../css/style.css H|logout.php H|../user-management_change-password.php H|../user-management_profile.php H|../dashboard_settings.php H|oc-balance_add.php H|oc-balance_summary.php
vti_cachedsvcrellinks:VX|NQSS|https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css NSSS|https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js NSSS|https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js NQSS|https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css FHUS|admin/madrasati/dashboard.php FHUS|admin/index.php FKUS|admin/madrasati/dashboard.php FKUS|admin/madrasati/dashboard.php FHUS|admin/madrasati/account-transaction_add-transaction.php FHUS|admin/madrasati/account-transaction_summary.php FKUS|admin/madrasati/dashboard.php FHUS|admin/madrasati/account-transaction_add-transaction.php FHUS|admin/madrasati/account-transaction_annual_summary.php FKUS|admin/madrasati/dashboard.php FHUS|admin/madrasati/payslip_select-staff.php FHUS|admin/madrasati/payslip_summary.php FHUS|admin/madrasati/report_expense-report.php FKUS|admin/madrasati/dashboard.php FKUS|admin/madrasati/dashboard.php FHUS|admin/madrasati/invoice_select-student.php FHUS|admin/madrasati/invoice_select-invoice.php FKUS|admin/madrasati/dashboard.php FHUS|admin/madrasati/payment_select-student.php FHUS|admin/madrasati/payment_summary.php FKUS|admin/madrasati/dashboard.php FHUS|admin/madrasati/account-transaction_incomes_add-transaction.php FHUS|admin/madrasati/account-transaction_incomes.php FHUS|admin/madrasati/report_payment-report.php FKUS|admin/madrasati/dashboard.php FHUS|admin/madrasati/account-statement.php FHUS|admin/madrasati/account-statement_search.php FKUS|admin/madrasati/dashboard.php FHUS|admin/madrasati/invoice_paid.php FHUS|admin/madrasati/invoice_partial.php FHUS|admin/madrasati/invoice_unpaid.php FKUS|admin/madrasati/dashboard.php FKUS|admin/madrasati/dashboard.php FHUS|admin/madrasati/student_new-account.php FHUS|admin/madrasati/student_manage-account.php FKUS|admin/madrasati/dashboard.php FKUS|admin/madrasati/dashboard.php FHUS|admin/madrasati/staff_new-account.php FHUS|admin/madrasati/staff_manage-account.php FHUS|admin/madrasati/staff-directory.php FKUS|admin/madrasati/dashboard.php FKUS|admin/madrasati/dashboard.php FHUS|admin/madrasati/report_account-statement-report.php FHUS|admin/madrasati/report_account-statement-report-annual.php FHUS|admin/madrasati/account-statement.php FHUS|admin/madrasati/report_expense-report.php FHUS|admin/madrasati/report_payment-report.php FHUS|admin/madrasati/report_payslip-report.php FHUS|admin/madrasati/report_annual-fees-report.php FHUS|admin/madrasati/report_term-fees-report.php FHUS|admin/nuhsark/dashboard.php FHUS|admin/logout.php NQUS|admin/css/style.css FHUS|admin/madrasati/logout.php FHUS|admin/user-management_change-password.php FHUS|admin/user-management_profile.php FHUS|admin/dashboard_settings.php FHUS|admin/madrasati/oc-balance_add.php FHUS|admin/madrasati/oc-balance_summary.php
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=utf-8
vti_charset:SR|utf-8
vti_title:SR|Nuh's Ark Islamic Montessori School
vti_backlinkinfo:VX|admin/madrasati/dashboard.php
